#!/bin/bash
# Script Name: debian-iptables.sh

./iptables-rules

# Save the rules, Debian does not require restart
/sbin/iptables-save > /etc/iptables.up.rules

# Run iptables on startup
cp ./debian-iptables-load /etc/network/if-pre-up.d/iptables
chmod +x /etc/network/if-pre-up.d/iptables
