#!/bin/bash
# Script Name: rhel-iptables.sh
#
# This script should not be run directly, it is called by rhel-iptables or
# debian-iptables, which ensure the rules are saved correctly for the distro

IPT=/sbin/iptables

$IPT -A INPUT -p tcp --tcp-flags ALL NONE -j DROP
$IPT -A INPUT -p tcp ! --syn -m state --state NEW -j DROP
$IPT -A INPUT -p tcp --tcp-flags ALL ALL -j DROP

$IPT -A INPUT -i lo -j ACCEPT     # localhost loopback
$IPT -A INPUT -p tcp -m tcp --dport 80 -j ACCEPT     # HTTP
$IPT -A INPUT -p tcp -m tcp --dport 443 -j ACCEPT    # HTTPS
#$IPT -A INPUT -p tcp -m tcp --dport 25 -j ACCEPT     # SMTP
#$IPT -A INPUT -p tcp -m tcp --dport 465 -j ACCEPT    # SMTPS
#$IPT -A INPUT -p tcp -m tcp --dport 110 -j ACCEPT    # IMAP
#$IPT -A INPUT -p tcp -m tcp --dport 995 -j ACCEPT    # IMAPS
#$IPT -A INPUT -p tcp -m tcp --dport 143 -j ACCEPT    # POP3
#$IPT -A INPUT -p tcp -m tcp --dport 993 -j ACCEPT    # POP3S

#$IPT -A INPUT -p tcp -m tcp --dport 22 -j ACCEPT
#$IPT -A INPUT -p tcp -m tcp --dport 22522 -j ACCEPT

$IPT -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
$IPT -P OUTPUT ACCEPT
$IPT -P INPUT DROP
