#!/bin/bash
# Shell script to Finding ALL Superuser Accounts
# Useful to improve system security.
# Copyright (c) 2005 nixCraft
# This script is licensed under GNU GPL version 2.0 or above
# For more info, please visit:
#            http://cyberciti.biz/shell_scripting/bmsinstall.php
# -------------------------------------------------------------------------
# This script is part of nixCraft shell script collection (NSSC)
# Visit http://bash.cyberciti.biz/ for more information.
# -------------------------------------------------------------------------
grep -v -E "^#" /etc/passwd | awk -F: '$3 == 0 { print $1}'
